-- ==========================================
-- ArenaSync Supabase PostgreSQL Schema & Seed
-- ==========================================

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS sports (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tournaments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  sport_id BIGINT REFERENCES sports(id) ON DELETE SET NULL,
  location TEXT,
  state TEXT,
  district TEXT,
  ground_name TEXT,
  date DATE,
  last_registration_date DATE,
  entry_fee NUMERIC DEFAULT 0,
  prize_amount NUMERIC DEFAULT 0,
  max_teams INTEGER DEFAULT 16,
  registered_teams INTEGER DEFAULT 0,
  status TEXT DEFAULT 'upcoming',
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS teams (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  tournament_id BIGINT REFERENCES tournaments(id) ON DELETE CASCADE,
  "group" TEXT,
  members INTEGER DEFAULT 11,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_tournaments_sport_id ON tournaments(sport_id);
CREATE INDEX IF NOT EXISTS idx_tournaments_status ON tournaments(status);
CREATE INDEX IF NOT EXISTS idx_tournaments_date ON tournaments(date);
CREATE INDEX IF NOT EXISTS idx_teams_tournament_id ON teams(tournament_id);

-- 3. Row Level Security (RLS) Policies
ALTER TABLE sports ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournaments ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on sports" ON sports FOR SELECT USING (true);
CREATE POLICY "Allow public read access on tournaments" ON tournaments FOR SELECT USING (true);
CREATE POLICY "Allow public read access on teams" ON teams FOR SELECT USING (true);

CREATE POLICY "Allow insert on tournaments" ON tournaments FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update on tournaments" ON tournaments FOR UPDATE USING (true);
CREATE POLICY "Allow insert on teams" ON teams FOR INSERT WITH CHECK (true);

-- 4. Seed Data: Sports (10 rows)
INSERT INTO sports (id, name, image) VALUES
  (1, 'Soccer', 'soccer.jpg'),
  (2, 'Basketball', 'basketball.jpg'),
  (3, 'Tennis', 'tennis.jpg'),
  (4, 'Cricket', 'cricket.jpg'),
  (5, 'Kabaddi', 'kabaddi.jpg'),
  (6, 'Volleyball', 'volleyball.jpg'),
  (7, 'Hockey', 'hockey.jpg'),
  (8, 'Badminton', 'badminton.jpg'),
  (9, 'Table Tennis', 'tabletennis.jpg'),
  (10, 'Swimming', 'swimming.jpg')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, image = EXCLUDED.image;

SELECT setval('sports_id_seq', (SELECT MAX(id) FROM sports));

-- 5. Seed Data: Tournaments (150 rows)
INSERT INTO tournaments (id, name, sport_id, location, state, district, ground_name, date, last_registration_date, entry_fee, prize_amount, max_teams, registered_teams, status, description) VALUES
  (1, 'Soccer Tournament 1', 1, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-05-24', '2026-05-15', 1878, 37560, 20, 7, 'post', 'Exciting Soccer tournament in Hyderabad.'),
  (2, 'Soccer Tournament 2', 1, 'Bangalore', 'Karnataka', 'Bangalore Urban', 'Sree Kanteerava Stadium', '2026-01-15', '2025-12-17', 3591, 71820, 20, 16, 'post', 'Exciting Soccer tournament in Bangalore.'),
  (3, 'Soccer Tournament 3', 1, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-11-01', '2026-10-14', 3901, 78020, 20, 17, 'post', 'Exciting Soccer tournament in Chennai.'),
  (4, 'Soccer Tournament 4', 1, 'Mumbai', 'Maharashtra', 'Mumbai Suburban', 'Cricket Club of India', '2026-02-07', '2026-01-10', 3382, 67640, 20, 11, 'post', 'Exciting Soccer tournament in Mumbai.'),
  (5, 'Soccer Tournament 5', 1, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-11-02', '2026-10-20', 5643, 112860, 20, 3, 'post', 'Exciting Soccer tournament in Hyderabad.'),
  (6, 'Soccer Tournament 6', 1, 'Mumbai', 'Maharashtra', 'Mumbai Suburban', 'Cricket Club of India', '2026-11-10', '2026-10-14', 1636, 32720, 20, 20, 'full', 'Exciting Soccer tournament in Mumbai.'),
  (7, 'Soccer Tournament 7', 1, 'Jaipur', 'Rajasthan', 'Jaipur', 'Sawai Mansingh Stadium', '2025-12-31', '2025-12-17', 1177, 23540, 20, 20, 'full', 'Exciting Soccer tournament in Jaipur.'),
  (8, 'Soccer Tournament 8', 1, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-10-02', '2026-09-24', 5779, 115580, 20, 20, 'full', 'Exciting Soccer tournament in Delhi.'),
  (9, 'Soccer Tournament 9', 1, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-05-23', '2026-04-25', 4816, 96320, 20, 20, 'full', 'Exciting Soccer tournament in Madurai.'),
  (10, 'Soccer Tournament 10', 1, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-02-06', '2026-01-16', 1732, 34640, 20, 20, 'full', 'Exciting Soccer tournament in Madurai.'),
  (11, 'Soccer Tournament 11', 1, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-07-13', '2026-06-16', 3632, 72640, 20, 16, 'future', 'Exciting Soccer tournament in Kolkata.'),
  (12, 'Soccer Tournament 12', 1, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-10-10', '2026-10-09', 2080, 41600, 20, 17, 'future', 'Exciting Soccer tournament in Madurai.'),
  (13, 'Soccer Tournament 13', 1, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-07-21', '2026-07-06', 3937, 78740, 20, 11, 'future', 'Exciting Soccer tournament in Ahmedabad.'),
  (14, 'Soccer Tournament 14', 1, 'Jaipur', 'Rajasthan', 'Jaipur', 'Sawai Mansingh Stadium', '2026-04-18', '2026-03-25', 5341, 106820, 20, 10, 'future', 'Exciting Soccer tournament in Jaipur.'),
  (15, 'Soccer Tournament 15', 1, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-11-15', '2026-10-16', 5606, 112120, 20, 13, 'future', 'Exciting Soccer tournament in Pune.'),
  (16, 'Basketball Tournament 1', 2, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-10-08', '2026-09-19', 4902, 98040, 20, 12, 'post', 'Exciting Basketball tournament in Madurai.'),
  (17, 'Basketball Tournament 2', 2, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-07-03', '2026-06-18', 2327, 46540, 20, 16, 'post', 'Exciting Basketball tournament in Madurai.'),
  (18, 'Basketball Tournament 3', 2, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-05-13', '2026-04-16', 4076, 81520, 20, 14, 'post', 'Exciting Basketball tournament in Hyderabad.'),
  (19, 'Basketball Tournament 4', 2, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-10-06', '2026-09-17', 2950, 59000, 20, 2, 'post', 'Exciting Basketball tournament in Kolkata.'),
  (20, 'Basketball Tournament 5', 2, 'Mumbai', 'Maharashtra', 'Mumbai Suburban', 'Cricket Club of India', '2026-01-25', '2026-01-13', 1339, 26780, 20, 2, 'post', 'Exciting Basketball tournament in Mumbai.'),
  (21, 'Basketball Tournament 6', 2, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-07-01', '2026-06-04', 3322, 66440, 20, 20, 'full', 'Exciting Basketball tournament in Ahmedabad.'),
  (22, 'Basketball Tournament 7', 2, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-07-20', '2026-06-30', 4110, 82200, 20, 20, 'full', 'Exciting Basketball tournament in Kolkata.'),
  (23, 'Basketball Tournament 8', 2, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-09-06', '2026-08-13', 5524, 110480, 20, 20, 'full', 'Exciting Basketball tournament in Delhi.'),
  (24, 'Basketball Tournament 9', 2, 'Jaipur', 'Rajasthan', 'Jaipur', 'Sawai Mansingh Stadium', '2026-07-05', '2026-06-16', 1736, 34720, 20, 20, 'full', 'Exciting Basketball tournament in Jaipur.'),
  (25, 'Basketball Tournament 10', 2, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-07-24', '2026-07-09', 4252, 85040, 20, 20, 'full', 'Exciting Basketball tournament in Delhi.'),
  (26, 'Basketball Tournament 11', 2, 'Bangalore', 'Karnataka', 'Bangalore Urban', 'Sree Kanteerava Stadium', '2026-06-13', '2026-05-26', 5175, 103500, 20, 16, 'future', 'Exciting Basketball tournament in Bangalore.'),
  (27, 'Basketball Tournament 12', 2, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-09-27', '2026-09-17', 2926, 58520, 20, 3, 'future', 'Exciting Basketball tournament in Pune.'),
  (28, 'Basketball Tournament 13', 2, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-05-07', '2026-04-29', 3774, 75480, 20, 10, 'future', 'Exciting Basketball tournament in Pune.'),
  (29, 'Basketball Tournament 14', 2, 'Bangalore', 'Karnataka', 'Bangalore Urban', 'Sree Kanteerava Stadium', '2026-03-20', '2026-03-16', 3759, 75180, 20, 5, 'future', 'Exciting Basketball tournament in Bangalore.'),
  (30, 'Basketball Tournament 15', 2, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-04-23', '2026-04-08', 4663, 93260, 20, 13, 'future', 'Exciting Basketball tournament in Hyderabad.'),
  (31, 'Tennis Tournament 1', 3, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-06-07', '2026-05-13', 1728, 34560, 20, 10, 'post', 'Exciting Tennis tournament in Madurai.'),
  (32, 'Tennis Tournament 2', 3, 'Mumbai', 'Maharashtra', 'Mumbai Suburban', 'Cricket Club of India', '2026-02-20', '2026-02-11', 5538, 110760, 20, 9, 'post', 'Exciting Tennis tournament in Mumbai.'),
  (33, 'Tennis Tournament 3', 3, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-07-12', '2026-07-08', 2149, 42980, 20, 7, 'post', 'Exciting Tennis tournament in Ahmedabad.'),
  (34, 'Tennis Tournament 4', 3, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-04-02', '2026-03-07', 4773, 95460, 20, 7, 'post', 'Exciting Tennis tournament in Kolkata.'),
  (35, 'Tennis Tournament 5', 3, 'Bangalore', 'Karnataka', 'Bangalore Urban', 'Sree Kanteerava Stadium', '2026-05-14', '2026-05-05', 4893, 97860, 20, 8, 'post', 'Exciting Tennis tournament in Bangalore.'),
  (36, 'Tennis Tournament 6', 3, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-10-24', '2026-10-08', 4533, 90660, 20, 20, 'full', 'Exciting Tennis tournament in Ahmedabad.'),
  (37, 'Tennis Tournament 7', 3, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-09-27', '2026-09-03', 4638, 92760, 20, 20, 'full', 'Exciting Tennis tournament in Ahmedabad.'),
  (38, 'Tennis Tournament 8', 3, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-02-05', '2026-01-27', 2380, 47600, 20, 20, 'full', 'Exciting Tennis tournament in Madurai.'),
  (39, 'Tennis Tournament 9', 3, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-06-12', '2026-05-24', 3486, 69720, 20, 20, 'full', 'Exciting Tennis tournament in Hyderabad.'),
  (40, 'Tennis Tournament 10', 3, 'Mumbai', 'Maharashtra', 'Mumbai Suburban', 'Cricket Club of India', '2026-08-26', '2026-08-13', 5526, 110520, 20, 20, 'full', 'Exciting Tennis tournament in Mumbai.'),
  (41, 'Tennis Tournament 11', 3, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-12-11', '2026-11-25', 2647, 52940, 20, 12, 'future', 'Exciting Tennis tournament in Kolkata.'),
  (42, 'Tennis Tournament 12', 3, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-09-15', '2026-09-09', 5865, 117300, 20, 6, 'future', 'Exciting Tennis tournament in Ahmedabad.'),
  (43, 'Tennis Tournament 13', 3, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-12-14', '2026-12-13', 1704, 34080, 20, 8, 'future', 'Exciting Tennis tournament in Ahmedabad.'),
  (44, 'Tennis Tournament 14', 3, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-02-23', '2026-02-03', 1254, 25080, 20, 11, 'future', 'Exciting Tennis tournament in Ahmedabad.'),
  (45, 'Tennis Tournament 15', 3, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-12-12', '2026-11-17', 1112, 22240, 20, 2, 'future', 'Exciting Tennis tournament in Ahmedabad.'),
  (46, 'Cricket Tournament 1', 4, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-05-18', '2026-05-03', 5363, 107260, 20, 13, 'post', 'Exciting Cricket tournament in Pune.'),
  (47, 'Cricket Tournament 2', 4, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-04-26', '2026-04-05', 5667, 113340, 20, 12, 'post', 'Exciting Cricket tournament in Hyderabad.'),
  (48, 'Cricket Tournament 3', 4, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-06-04', '2026-05-10', 1786, 35720, 20, 19, 'post', 'Exciting Cricket tournament in Chennai.'),
  (49, 'Cricket Tournament 4', 4, 'Jaipur', 'Rajasthan', 'Jaipur', 'Sawai Mansingh Stadium', '2026-02-11', '2026-01-28', 3075, 61500, 20, 5, 'post', 'Exciting Cricket tournament in Jaipur.'),
  (50, 'Cricket Tournament 5', 4, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-06-07', '2026-05-24', 3660, 73200, 20, 14, 'post', 'Exciting Cricket tournament in Pune.'),
  (51, 'Cricket Tournament 6', 4, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-04-14', '2026-03-26', 1236, 24720, 20, 20, 'full', 'Exciting Cricket tournament in Hyderabad.'),
  (52, 'Cricket Tournament 7', 4, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-01-24', '2026-01-21', 2467, 49340, 20, 20, 'full', 'Exciting Cricket tournament in Kolkata.'),
  (53, 'Cricket Tournament 8', 4, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-01-11', '2025-12-16', 4854, 97080, 20, 20, 'full', 'Exciting Cricket tournament in Kolkata.'),
  (54, 'Cricket Tournament 9', 4, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-01-09', '2025-12-27', 2410, 48200, 20, 20, 'full', 'Exciting Cricket tournament in Chennai.'),
  (55, 'Cricket Tournament 10', 4, 'Jaipur', 'Rajasthan', 'Jaipur', 'Sawai Mansingh Stadium', '2026-09-13', '2026-08-18', 2286, 45720, 20, 20, 'full', 'Exciting Cricket tournament in Jaipur.'),
  (56, 'Cricket Tournament 11', 4, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-03-27', '2026-03-10', 2234, 44680, 20, 6, 'future', 'Exciting Cricket tournament in Chennai.'),
  (57, 'Cricket Tournament 12', 4, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-05-14', '2026-05-09', 1387, 27740, 20, 3, 'future', 'Exciting Cricket tournament in Madurai.'),
  (58, 'Cricket Tournament 13', 4, 'Jaipur', 'Rajasthan', 'Jaipur', 'Sawai Mansingh Stadium', '2026-09-27', '2026-08-31', 2074, 41480, 20, 15, 'future', 'Exciting Cricket tournament in Jaipur.'),
  (59, 'Cricket Tournament 14', 4, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-04-22', '2026-03-26', 3214, 64280, 20, 3, 'future', 'Exciting Cricket tournament in Pune.'),
  (60, 'Cricket Tournament 15', 4, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-04-08', '2026-03-28', 1161, 23220, 20, 5, 'future', 'Exciting Cricket tournament in Madurai.'),
  (61, 'Kabaddi Tournament 1', 5, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-05-01', '2026-04-17', 2298, 45960, 20, 0, 'post', 'Exciting Kabaddi tournament in Hyderabad.'),
  (62, 'Kabaddi Tournament 2', 5, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-08-17', '2026-08-10', 1902, 38040, 20, 13, 'post', 'Exciting Kabaddi tournament in Ahmedabad.'),
  (63, 'Kabaddi Tournament 3', 5, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-12-08', '2026-11-20', 3629, 72580, 20, 6, 'post', 'Exciting Kabaddi tournament in Pune.'),
  (64, 'Kabaddi Tournament 4', 5, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-05-11', '2026-04-22', 3683, 73660, 20, 10, 'post', 'Exciting Kabaddi tournament in Kolkata.'),
  (65, 'Kabaddi Tournament 5', 5, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-02-18', '2026-02-06', 5159, 103180, 20, 17, 'post', 'Exciting Kabaddi tournament in Chennai.'),
  (66, 'Kabaddi Tournament 6', 5, 'Jaipur', 'Rajasthan', 'Jaipur', 'Sawai Mansingh Stadium', '2026-06-25', '2026-06-15', 3448, 68960, 20, 20, 'full', 'Exciting Kabaddi tournament in Jaipur.'),
  (67, 'Kabaddi Tournament 7', 5, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-11-08', '2026-11-02', 5290, 105800, 20, 20, 'full', 'Exciting Kabaddi tournament in Ahmedabad.'),
  (68, 'Kabaddi Tournament 8', 5, 'Jaipur', 'Rajasthan', 'Jaipur', 'Sawai Mansingh Stadium', '2026-06-27', '2026-06-21', 4370, 87400, 20, 20, 'full', 'Exciting Kabaddi tournament in Jaipur.'),
  (69, 'Kabaddi Tournament 9', 5, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-01-13', '2025-12-14', 1766, 35320, 20, 20, 'full', 'Exciting Kabaddi tournament in Kolkata.'),
  (70, 'Kabaddi Tournament 10', 5, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-05-19', '2026-05-11', 3850, 77000, 20, 20, 'full', 'Exciting Kabaddi tournament in Ahmedabad.'),
  (71, 'Kabaddi Tournament 11', 5, 'Bangalore', 'Karnataka', 'Bangalore Urban', 'Sree Kanteerava Stadium', '2026-03-09', '2026-02-10', 5744, 114880, 20, 1, 'future', 'Exciting Kabaddi tournament in Bangalore.'),
  (72, 'Kabaddi Tournament 12', 5, 'Jaipur', 'Rajasthan', 'Jaipur', 'Sawai Mansingh Stadium', '2026-01-24', '2026-01-23', 2847, 56940, 20, 8, 'future', 'Exciting Kabaddi tournament in Jaipur.'),
  (73, 'Kabaddi Tournament 13', 5, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-08-07', '2026-08-02', 4191, 83820, 20, 12, 'future', 'Exciting Kabaddi tournament in Madurai.'),
  (74, 'Kabaddi Tournament 14', 5, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-05-18', '2026-05-04', 3160, 63200, 20, 2, 'future', 'Exciting Kabaddi tournament in Kolkata.'),
  (75, 'Kabaddi Tournament 15', 5, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-06-03', '2026-05-08', 2928, 58560, 20, 4, 'future', 'Exciting Kabaddi tournament in Chennai.'),
  (76, 'Volleyball Tournament 1', 6, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-11-01', '2026-10-31', 1200, 24000, 20, 10, 'post', 'Exciting Volleyball tournament in Chennai.'),
  (77, 'Volleyball Tournament 2', 6, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-07-05', '2026-06-13', 4117, 82340, 20, 4, 'post', 'Exciting Volleyball tournament in Chennai.'),
  (78, 'Volleyball Tournament 3', 6, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-08-22', '2026-08-08', 5679, 113580, 20, 0, 'post', 'Exciting Volleyball tournament in Madurai.'),
  (79, 'Volleyball Tournament 4', 6, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-06-20', '2026-06-14', 5044, 100880, 20, 18, 'post', 'Exciting Volleyball tournament in Pune.'),
  (80, 'Volleyball Tournament 5', 6, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-11-26', '2026-10-31', 3492, 69840, 20, 10, 'post', 'Exciting Volleyball tournament in Hyderabad.'),
  (81, 'Volleyball Tournament 6', 6, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-08-07', '2026-07-16', 1602, 32040, 20, 20, 'full', 'Exciting Volleyball tournament in Madurai.'),
  (82, 'Volleyball Tournament 7', 6, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-02-11', '2026-01-18', 3058, 61160, 20, 20, 'full', 'Exciting Volleyball tournament in Hyderabad.'),
  (83, 'Volleyball Tournament 8', 6, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-04-26', '2026-04-23', 4940, 98800, 20, 20, 'full', 'Exciting Volleyball tournament in Kolkata.'),
  (84, 'Volleyball Tournament 9', 6, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-08-21', '2026-08-12', 5561, 111220, 20, 20, 'full', 'Exciting Volleyball tournament in Kolkata.'),
  (85, 'Volleyball Tournament 10', 6, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-11-30', '2026-11-21', 1640, 32800, 20, 20, 'full', 'Exciting Volleyball tournament in Pune.'),
  (86, 'Volleyball Tournament 11', 6, 'Mumbai', 'Maharashtra', 'Mumbai Suburban', 'Cricket Club of India', '2026-03-04', '2026-03-01', 4369, 87380, 20, 15, 'future', 'Exciting Volleyball tournament in Mumbai.'),
  (87, 'Volleyball Tournament 12', 6, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-08-18', '2026-07-30', 2309, 46180, 20, 9, 'future', 'Exciting Volleyball tournament in Ahmedabad.'),
  (88, 'Volleyball Tournament 13', 6, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-04-24', '2026-03-31', 4018, 80360, 20, 14, 'future', 'Exciting Volleyball tournament in Madurai.'),
  (89, 'Volleyball Tournament 14', 6, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-06-23', '2026-06-20', 4292, 85840, 20, 5, 'future', 'Exciting Volleyball tournament in Delhi.'),
  (90, 'Volleyball Tournament 15', 6, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-06-11', '2026-06-09', 2709, 54180, 20, 10, 'future', 'Exciting Volleyball tournament in Kolkata.'),
  (91, 'Hockey Tournament 1', 7, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-04-25', '2026-04-01', 2688, 53760, 20, 15, 'post', 'Exciting Hockey tournament in Ahmedabad.'),
  (92, 'Hockey Tournament 2', 7, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-02-07', '2026-01-13', 4137, 82740, 20, 9, 'post', 'Exciting Hockey tournament in Ahmedabad.'),
  (93, 'Hockey Tournament 3', 7, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-05-05', '2026-04-26', 3449, 68980, 20, 5, 'post', 'Exciting Hockey tournament in Madurai.'),
  (94, 'Hockey Tournament 4', 7, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-07-25', '2026-06-27', 4708, 94160, 20, 18, 'post', 'Exciting Hockey tournament in Kolkata.'),
  (95, 'Hockey Tournament 5', 7, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-04-24', '2026-04-13', 5131, 102620, 20, 0, 'post', 'Exciting Hockey tournament in Pune.'),
  (96, 'Hockey Tournament 6', 7, 'Mumbai', 'Maharashtra', 'Mumbai Suburban', 'Cricket Club of India', '2026-07-23', '2026-07-20', 5909, 118180, 20, 20, 'full', 'Exciting Hockey tournament in Mumbai.'),
  (97, 'Hockey Tournament 7', 7, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-12-05', '2026-11-26', 5551, 111020, 20, 20, 'full', 'Exciting Hockey tournament in Hyderabad.'),
  (98, 'Hockey Tournament 8', 7, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-01-22', '2025-12-26', 3081, 61620, 20, 20, 'full', 'Exciting Hockey tournament in Kolkata.'),
  (99, 'Hockey Tournament 9', 7, 'Bangalore', 'Karnataka', 'Bangalore Urban', 'Sree Kanteerava Stadium', '2026-10-12', '2026-09-30', 5856, 117120, 20, 20, 'full', 'Exciting Hockey tournament in Bangalore.'),
  (100, 'Hockey Tournament 10', 7, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-10-24', '2026-10-23', 3483, 69660, 20, 20, 'full', 'Exciting Hockey tournament in Ahmedabad.'),
  (101, 'Hockey Tournament 11', 7, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-02-13', '2026-02-07', 5608, 112160, 20, 6, 'future', 'Exciting Hockey tournament in Hyderabad.'),
  (102, 'Hockey Tournament 12', 7, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-08-20', '2026-08-09', 3162, 63240, 20, 15, 'future', 'Exciting Hockey tournament in Delhi.'),
  (103, 'Hockey Tournament 13', 7, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-02-01', '2026-01-21', 5876, 117520, 20, 5, 'future', 'Exciting Hockey tournament in Kolkata.'),
  (104, 'Hockey Tournament 14', 7, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-02-13', '2026-02-06', 5793, 115860, 20, 4, 'future', 'Exciting Hockey tournament in Delhi.'),
  (105, 'Hockey Tournament 15', 7, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-06-11', '2026-05-19', 4115, 82300, 20, 16, 'future', 'Exciting Hockey tournament in Kolkata.'),
  (106, 'Badminton Tournament 1', 8, 'Mumbai', 'Maharashtra', 'Mumbai Suburban', 'Cricket Club of India', '2026-04-27', '2026-04-01', 5611, 112220, 20, 14, 'post', 'Exciting Badminton tournament in Mumbai.'),
  (107, 'Badminton Tournament 2', 8, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-12-06', '2026-12-05', 1079, 21580, 20, 6, 'post', 'Exciting Badminton tournament in Kolkata.'),
  (108, 'Badminton Tournament 3', 8, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-10-25', '2026-10-01', 3514, 70280, 20, 19, 'post', 'Exciting Badminton tournament in Pune.'),
  (109, 'Badminton Tournament 4', 8, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-03-24', '2026-03-22', 3846, 76920, 20, 7, 'post', 'Exciting Badminton tournament in Pune.'),
  (110, 'Badminton Tournament 5', 8, 'Jaipur', 'Rajasthan', 'Jaipur', 'Sawai Mansingh Stadium', '2026-09-20', '2026-09-17', 3405, 68100, 20, 2, 'post', 'Exciting Badminton tournament in Jaipur.'),
  (111, 'Badminton Tournament 6', 8, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-10-08', '2026-09-22', 5427, 108540, 20, 20, 'full', 'Exciting Badminton tournament in Pune.'),
  (112, 'Badminton Tournament 7', 8, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-09-23', '2026-09-05', 5798, 115960, 20, 20, 'full', 'Exciting Badminton tournament in Pune.'),
  (113, 'Badminton Tournament 8', 8, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-11-02', '2026-10-24', 4707, 94140, 20, 20, 'full', 'Exciting Badminton tournament in Delhi.'),
  (114, 'Badminton Tournament 9', 8, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-10-12', '2026-09-13', 1056, 21120, 20, 20, 'full', 'Exciting Badminton tournament in Hyderabad.'),
  (115, 'Badminton Tournament 10', 8, 'Bangalore', 'Karnataka', 'Bangalore Urban', 'Sree Kanteerava Stadium', '2026-12-12', '2026-11-21', 4947, 98940, 20, 20, 'full', 'Exciting Badminton tournament in Bangalore.'),
  (116, 'Badminton Tournament 11', 8, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-09-24', '2026-09-15', 2051, 41020, 20, 13, 'future', 'Exciting Badminton tournament in Hyderabad.'),
  (117, 'Badminton Tournament 12', 8, 'Kolkata', 'West Bengal', 'Kolkata', 'Eden Gardens', '2026-11-05', '2026-10-13', 3989, 79780, 20, 14, 'future', 'Exciting Badminton tournament in Kolkata.'),
  (118, 'Badminton Tournament 13', 8, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-09-26', '2026-08-30', 3116, 62320, 20, 13, 'future', 'Exciting Badminton tournament in Madurai.'),
  (119, 'Badminton Tournament 14', 8, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-11-13', '2026-10-16', 5976, 119520, 20, 18, 'future', 'Exciting Badminton tournament in Delhi.'),
  (120, 'Badminton Tournament 15', 8, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-09-13', '2026-08-26', 5713, 114260, 20, 13, 'future', 'Exciting Badminton tournament in Delhi.'),
  (121, 'Table Tennis Tournament 1', 9, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-01-05', '2025-12-13', 4493, 89860, 20, 17, 'post', 'Exciting Table Tennis tournament in Pune.'),
  (122, 'Table Tennis Tournament 2', 9, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-07-24', '2026-07-17', 5013, 100260, 20, 4, 'post', 'Exciting Table Tennis tournament in Hyderabad.'),
  (123, 'Table Tennis Tournament 3', 9, 'Bangalore', 'Karnataka', 'Bangalore Urban', 'Sree Kanteerava Stadium', '2026-12-04', '2026-11-12', 4531, 90620, 20, 7, 'post', 'Exciting Table Tennis tournament in Bangalore.'),
  (124, 'Table Tennis Tournament 4', 9, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-04-15', '2026-03-23', 1452, 29040, 20, 3, 'post', 'Exciting Table Tennis tournament in Hyderabad.'),
  (125, 'Table Tennis Tournament 5', 9, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-07-14', '2026-06-24', 1531, 30620, 20, 17, 'post', 'Exciting Table Tennis tournament in Delhi.'),
  (126, 'Table Tennis Tournament 6', 9, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-03-31', '2026-03-08', 2435, 48700, 20, 20, 'full', 'Exciting Table Tennis tournament in Pune.'),
  (127, 'Table Tennis Tournament 7', 9, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-07-11', '2026-06-28', 3604, 72080, 20, 20, 'full', 'Exciting Table Tennis tournament in Chennai.'),
  (128, 'Table Tennis Tournament 8', 9, 'Bangalore', 'Karnataka', 'Bangalore Urban', 'Sree Kanteerava Stadium', '2026-06-08', '2026-05-23', 2464, 49280, 20, 20, 'full', 'Exciting Table Tennis tournament in Bangalore.'),
  (129, 'Table Tennis Tournament 9', 9, 'Pune', 'Maharashtra', 'Pune', 'Shaba Cricket Stadium', '2026-07-04', '2026-06-09', 4416, 88320, 20, 20, 'full', 'Exciting Table Tennis tournament in Pune.'),
  (130, 'Table Tennis Tournament 10', 9, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-01-05', '2025-12-24', 2632, 52640, 20, 20, 'full', 'Exciting Table Tennis tournament in Chennai.'),
  (131, 'Table Tennis Tournament 11', 9, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-08-05', '2026-07-25', 1227, 24540, 20, 13, 'future', 'Exciting Table Tennis tournament in Chennai.'),
  (132, 'Table Tennis Tournament 12', 9, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-07-03', '2026-06-27', 5129, 102580, 20, 14, 'future', 'Exciting Table Tennis tournament in Ahmedabad.'),
  (133, 'Table Tennis Tournament 13', 9, 'Jaipur', 'Rajasthan', 'Jaipur', 'Sawai Mansingh Stadium', '2026-08-15', '2026-07-31', 3764, 75280, 20, 3, 'future', 'Exciting Table Tennis tournament in Jaipur.'),
  (134, 'Table Tennis Tournament 14', 9, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-05-05', '2026-04-05', 1538, 30760, 20, 13, 'future', 'Exciting Table Tennis tournament in Hyderabad.'),
  (135, 'Table Tennis Tournament 15', 9, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-10-13', '2026-09-22', 3635, 72700, 20, 13, 'future', 'Exciting Table Tennis tournament in Chennai.'),
  (136, 'Swimming Tournament 1', 10, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-03-31', '2026-03-21', 3124, 62480, 20, 11, 'post', 'Exciting Swimming tournament in Delhi.'),
  (137, 'Swimming Tournament 2', 10, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-06-02', '2026-05-31', 5695, 113900, 20, 3, 'post', 'Exciting Swimming tournament in Ahmedabad.'),
  (138, 'Swimming Tournament 3', 10, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-03-25', '2026-03-19', 1642, 32840, 20, 19, 'post', 'Exciting Swimming tournament in Delhi.'),
  (139, 'Swimming Tournament 4', 10, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-08-25', '2026-08-13', 3770, 75400, 20, 19, 'post', 'Exciting Swimming tournament in Ahmedabad.'),
  (140, 'Swimming Tournament 5', 10, 'Ahmedabad', 'Gujarat', 'Ahmedabad', 'Narendra Modi Stadium', '2026-07-22', '2026-07-21', 1322, 26440, 20, 1, 'post', 'Exciting Swimming tournament in Ahmedabad.'),
  (141, 'Swimming Tournament 6', 10, 'Bangalore', 'Karnataka', 'Bangalore Urban', 'Sree Kanteerava Stadium', '2026-06-21', '2026-06-14', 4025, 80500, 20, 20, 'full', 'Exciting Swimming tournament in Bangalore.'),
  (142, 'Swimming Tournament 7', 10, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-04-14', '2026-03-22', 5392, 107840, 20, 20, 'full', 'Exciting Swimming tournament in Madurai.'),
  (143, 'Swimming Tournament 8', 10, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-11-10', '2026-10-24', 1452, 29040, 20, 20, 'full', 'Exciting Swimming tournament in Hyderabad.'),
  (144, 'Swimming Tournament 9', 10, 'Delhi', 'Delhi', 'New Delhi', 'Thyagaraj Sports Complex', '2026-11-08', '2026-10-14', 3766, 75320, 20, 20, 'full', 'Exciting Swimming tournament in Delhi.'),
  (145, 'Swimming Tournament 10', 10, 'Chennai', 'Tamil Nadu', 'Chennai', 'M.A. Chidambaram Stadium', '2026-03-08', '2026-02-22', 1554, 31080, 20, 20, 'full', 'Exciting Swimming tournament in Chennai.'),
  (146, 'Swimming Tournament 11', 10, 'Madurai', 'Tamil Nadu', 'Madurai', 'Jawaharlal Nehru Stadium', '2026-11-26', '2026-11-21', 1042, 20840, 20, 0, 'future', 'Exciting Swimming tournament in Madurai.'),
  (147, 'Swimming Tournament 12', 10, 'Mumbai', 'Maharashtra', 'Mumbai Suburban', 'Cricket Club of India', '2026-09-06', '2026-09-02', 2654, 53080, 20, 6, 'future', 'Exciting Swimming tournament in Mumbai.'),
  (148, 'Swimming Tournament 13', 10, 'Mumbai', 'Maharashtra', 'Mumbai Suburban', 'Cricket Club of India', '2026-11-12', '2026-11-06', 3332, 66640, 20, 1, 'future', 'Exciting Swimming tournament in Mumbai.'),
  (149, 'Swimming Tournament 14', 10, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-07-06', '2026-06-24', 5638, 112760, 20, 7, 'future', 'Exciting Swimming tournament in Hyderabad.'),
  (150, 'Swimming Tournament 15', 10, 'Hyderabad', 'Telangana', 'Hyderabad', 'Rajiv Gandhi International Stadium', '2026-07-31', '2026-07-09', 2386, 47720, 20, 0, 'future', 'Exciting Swimming tournament in Hyderabad.')
ON CONFLICT (id) DO UPDATE SET 
  name = EXCLUDED.name, sport_id = EXCLUDED.sport_id, location = EXCLUDED.location,
  state = EXCLUDED.state, district = EXCLUDED.district, ground_name = EXCLUDED.ground_name,
  date = EXCLUDED.date, last_registration_date = EXCLUDED.last_registration_date,
  entry_fee = EXCLUDED.entry_fee, prize_amount = EXCLUDED.prize_amount,
  max_teams = EXCLUDED.max_teams, registered_teams = EXCLUDED.registered_teams,
  status = EXCLUDED.status, description = EXCLUDED.description;

SELECT setval('tournaments_id_seq', (SELECT MAX(id) FROM tournaments));
